package com.larr.app.e_commerce.security.jwt;

import java.io.IOException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.web.filter.OncePerRequestFilter;

import com.larr.app.e_commerce.security.service.UserDetailsServiceImpl;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * JWT authentication filter.
 * 
 * This filter runs on EVERY request and:
 * 1. Extracts JWT token from cookie
 * 2. Validates the token
 * 3. Loads user details from database
 * 4. Sets authentication in SecurityContext
 * 
 * This filter works for BOTH:
 * - Users who logged in with email/password (JWT generated at login)
 * - Users who logged in with OAuth2 (JWT generated by success handler)
 * 
 * Once JWT is set, the authentication method doesn't matter.
 */
public class JwtFilter extends OncePerRequestFilter {

    @Autowired
    private JwtUtils jwtUtils;

    @Autowired
    private UserDetailsServiceImpl userDetailsService;

    private static final Logger logger = LoggerFactory.getLogger(JwtFilter.class);

    /**
     * Filter logic executed on every request.
     * 
     * Flow:
     * 1. Request arrives with JWT cookie
     * 2. This filter executes FIRST (before controllers)
     * 3. Extract and validate JWT
     * 4. Load user from database using email in JWT
     * 5. Set authentication in SecurityContext
     * 6. Pass request to next filter/controller
     * 
     * Now controllers can access the authenticated user via:
     * Authentication auth = SecurityContextHolder.getContext().getAuthentication();
     * 
     * @param request     HTTP request
     * @param response    HTTP response
     * @param filterChain Filter chain to continue processing
     * @throws ServletException if servlet error occurs
     * @throws IOException      if I/O error occurs
     */
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
            throws ServletException, IOException {

        try {
            // Retrieve jwt token from the request
            String jwt = jwtUtils.getJwtFromCookie(request);

            // Check if the token exist and is valid
            if (jwt != null && jwtUtils.validateJwtToken(jwt)) {
                // Extract user email from token
                String userEmail = jwtUtils.getEmailFromJwtToken(jwt);

                // Load user's full details from the database
                UserDetails userDetails = userDetailsService.loadUserByUsername(userEmail);

                UsernamePasswordAuthenticationToken authentication = new UsernamePasswordAuthenticationToken(
                        userDetails, null, userDetails.getAuthorities()); // authentication object representing the user

                // attach the request details
                authentication.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));

                // Store the authenticated user in SecurityContent for controllers to retrieve
                SecurityContextHolder.getContext().setAuthentication(authentication);
            }
        } catch (JwtValidationException ex) {
            logger.error("JWT error: {}", ex.getMessage());
            request.setAttribute("jwtErrorMessage", ex.getMessage());

        } catch (Exception e) {
            logger.error("Cannot set user authentication: {}", e.getMessage());
        }

        filterChain.doFilter(request, response);
    }

}
